Upgrade to be terraform .12 compatible & other changes
cloudposse/terraform-aws-rds-cloudwatch-sns-alarms pull request #21
Opened 2020-07-02 18:33 UTC by caleb15

* Upgrades code to be terraform .12 compatible fixes #16
* Makes alarm names unique fixes #16
* __Breaking change__: requires sns topic param instead of creating one for the user. The user may already have a prexisting SNS topic that they might want to use. The repo should just concern itself with alarms and not with SNS.
* __Breaking change__: `db_instance_id` changed to `db_instance_ids` to support multiple db's
* add `alarm_period` and `alarm_evaluation_periods` params

We are running this change in production for [15Five](http://15five.com/).

2020-07-02 18:44 UTC, jamengual commented
> It shouldn't be assumed that it's okay to create a new topic - the user might want to reuse an existing sns topic for the RDS alarms. DEV-812

That is going to break other modules, could it be possible for you to use 
```
count = lenth(var.aws_sns_topic_arn) == 0 ? 0 : 1
```

2020-07-07 16:26 UTC, caleb15 commented
@jamengual Yeah, that should be possible. But either way the PR will still have a breaking change with the db instance id param.

I'm going to wait for a maintainer to respond to see what changes would be necessary to merge this in.

2020-07-07 17:14 UTC, jamengual commented
for the breaking changes I think is possible to maybe leave them empty or use a dynamic.

2020-07-07 17:17 UTC, nitrocode commented
To make this easier to review, could you put these changes in separate PRs?

We should at the very least have a separate PR for terraform11 to terraform12 changes to make this easier to review.

2020-07-07 18:14 UTC, 3h4x requested changes
Great work @caleb15 ! Thank you very much for PR.
These are great changes. I'm in favour of removing SNS topic creation without any backward compatibility. It should be fairly easy to migrate to new version thanks to variable `aws_sns_topic_arn`. In @cloudposse/contributors we are working on SNS module (initial PR already pushed) that should be used in conjunction with any CloudWatch alarm module.
Additionally it's a good change to monitor multiple RDS instances with this single module. We can avoid backward incompatibilty by reducing readablity of code and by having tech debt. Let's avoid that.
I left couple of questions and few improvements.  

PS: I'm going to push `pre-commit` to this repo for `tf fmt` and other lints. Please merge it to your PR when it's done.

2020-07-07 18:14 UTC, 3h4x commented on main.tf
>    event_categories = [
What is the reason behind removing other categories? 
I think it would be best to preserve previous list as a default. To customize you can create `event_categories` variable of `list(string)` type.

2020-07-07 18:14 UTC, 3h4x commented on variables.tf
empty line

2020-07-07 18:14 UTC, 3h4x commented on main.tf
>    name_prefix = "rds-event-sub"
Definitely we need a name prefix so all resources with names created by this module are aligned. Additionally I think `rds-sns-alarms` is more telling.
```suggestion
  name_prefix = "${var.name_prefix}rds-sns-alarms"
```

2020-07-07 18:14 UTC, 3h4x commented on variables.tf
> +  description = "The bla of the SNS topic you want to use for alerting"
"The bla"? I guess you mean ARN

2020-07-07 18:14 UTC, 3h4x commented on alarms.tf
> +  period              = var.period
unit = "Percent"

2020-07-07 18:14 UTC, 3h4x commented on alarms.tf
> +  period              = var.period
unit = "Percent"

2020-07-07 18:14 UTC, 3h4x commented on alarms.tf
> +  period              = var.period
unit = "Count"

2020-07-07 18:14 UTC, 3h4x commented on alarms.tf
> +  period              = var.period
unit = "Count"

2020-07-07 18:14 UTC, 3h4x commented on alarms.tf
> +  period              = var.period
unit = "Bytes"

2020-07-07 18:14 UTC, 3h4x commented on alarms.tf
> +  period              = var.period
unit = "Bytes"

2020-07-07 18:14 UTC, 3h4x commented on alarms.tf
> +  period              = var.period
unit = "Bytes"

2020-07-07 18:14 UTC, 3h4x commented on alarms.tf
> +  alarm_description   = "Average database storage burst balance over last ${var.period/60} minutes too low, expect a significant performance drop soon"
Please add `db_instance_id` to every alarm_description.

2020-09-15 23:07 UTC, caleb15 commented
Sorry for the delay on responding to the PR review, I've created a ticket so I remember to get to it eventually. Thanks for the review!

2020-10-27 05:54 UTC, macnibblet commented
@caleb15 Any chance we might see an update :)?

2020-10-27 17:40 UTC, caleb15 commented
@macnibblet yes, but it may take a while :see_no_evil: I have the email starred in my inbox along with 30 others.

2021-01-09 04:33 UTC, jamengual commented on main.tf
> +}
why all this have to be deleted?

2021-04-15 04:41 UTC, tovbinm commented
@caleb15 how far are you from finishing this one up?

2021-04-15 13:13 UTC, adamantike commented
Also waiting for this PR to be merged, to stop using a fork of this repo!

2021-04-15 20:18 UTC, Gowiem commented
@maximmi are you still the owning migration to 0.12 PRs? Any chance you could check this one out?

2021-04-20 08:22 UTC, maximmi requested changes
@caleb15 thank you for contribution
we have our standards for Terraform 0.12+ code, so that tests and github workflows should be in place. It might be hard to implement such things by you, so I will try to update your PR to respect all requirements.
For the reference you could pick any our repo with terraform 0.12+ support, for example: https://github.com/cloudposse/terraform-aws-s3-bucket

2024-03-02 01:23 UTC, closed without merging